Fixed maxOptions losing focus
yury-dymov/react-autocomplete-input pull request #92
Opened 2023-01-10 16:02 UTC by choisee

Fixed losing focus when using maxOptions - #73

2023-01-15 06:14 UTC, choisee commented
@yury-dymov Hi, Can you review this please?

2023-01-16 19:28 UTC, yury-dymov requested changes
Thank you for submitting patches! Please kindly address my feedback and I will merge it shortly.

2023-01-16 19:28 UTC, yury-dymov commented on src/AutoCompleteTextField.js
> +    const optionsCount = maxOptions === 0 || maxOptions > options.length ? options.length : maxOptions
nit: `;` in the end for consistency
Also a bit cleaner to my taste would be 
`const optionsCount = maxOptions > 0 ? Math.min(options.length, maxOptions) : options.length;`
It also covers case whenever folks passing `maxOptions = -1` expecting it to be infinity.

2023-01-16 19:28 UTC, yury-dymov commented on src/AutoCompleteTextField.js
> +          this.setState({ selection: ((optionsCount + selection) - 1) % optionsCount });
I know it's __currently__ an unreachable state for `optionsCount` to be zero as `helperVisible` would be false but it still makes me a bit nervous.  While it's not directly related to your change can we still update logic here and below to
```
case KEY_UP:
          event.preventDefault();
          if (optionsCount > 0) {
              this.setState({ selection: Math.max(0, optionsCount + selection - 1) % optionsCount });
         }
         break;
...
          }
```

2023-01-18 12:55 UTC, choisee commented
@yury-dymov Thanks for sincere review! Learned think about more cases. 
I applied feedbacks. Hope it could be helpful :)

2023-01-19 01:38 UTC, merged